#+ATTR_HTML: :alt wizard image :align center :width 200px :style display:inline;margin:-20px;
[[https://torsor.io/#community][file:./img/wizard2.png]]

~yaw~ is a domain-specific functional language for programming quantum
computers. This tutorial introduces some basic concepts, assuming
a first course in quantum computing but no further mathematical background.

* Basic concepts
-----
** Algebras
Usually, quantum computing is formulated in terms of states living in
a Hilbert space. In the algebraic approach, we instead use
/observables/ living in an /algebra/. A simple example is the /Pauli
algebra/ $\mathcal{A}_\text{Pauli}$, consisting of all single-qubit
operators. In ~yaw~, we define an object called ~pauli~ and give it
the /type/ of ~Algebra~ as follows:

#+BEGIN_SRC haskell
pauli :: Algebra
#+END_SRC

In general, types are categories of object; by convention, types are
capitalized and objects are not. To actually define
$\mathcal{A}_\text{Pauli}$, we use a /presentation/, consisting of
/generators/ (like ingredients in a recipe) and /relations/ (the
recipe itself). For instance, the Pauli algebra is generated by the
Pauli $X$ and Pauli $Z$, subject to the following relations:
\[
XZ = -ZX, \quad X^\dagger X = X^2 = Z^\dagger Z = Z^2 = I.
\]
Rather than list these individually, we have shorthands which state
that our generators are unitary ($G^\dagger G = I$ for all generators $G$), Hermitian
($G^\dagger = G$ for all $G$) and anticommute ($G'G = -GG'$ for all distinct
generators $G, G'$):

#+BEGIN_SRC haskell
pauli = Presentation gen [Hermitian gen, Unitary gen, AntiComm gen]
    where gen = [x, z]
#+END_SRC

Another way of viewing anticommutation is that $X$ and $Z$ commute up to
a phase $\omega = -1$, often called a /braiding/ relation:
\[
XZ = \omega ZX.
\]
We use ~Braid ω~ to indicate braiding relations. Similarly, instead of
the relation $G^2 = I$ (which results from unitarity) we can introduce
~Pow 2~ to indicate that generators square to the identity. As a
result of this new notation, we can immediately define the algebra of
/qudits/, the $d$-dimensional analogue of qubits:

#+BEGIN_SRC haskell
pauliQudit :: Integer -> Algebra
pauliQudit d = Presentation gen [Hermitian gen, Pow d gen, Braid ω gen]
    where gen = [x, z]
            ω = cis (-2 * pi / d)
#+END_SRC

Note that the type of ~pauliQudit~ is not an algebra, but rather a
/function/ from integers (the dimension) to an algebra (the
generalized Pauli algebra).
We symbolically denote this generalized
algebra $\mathcal{A}_d$, so for instance
$\mathcal{A}_2=\mathcal{A}_\text{Pauli}$.

** COMMENT Harmonic oscillator
As a final example, we can encode the commutation relations $[a,
a^\dagger] = I$ for a harmonic oscillator in braiding
form. Applying the /Baker-Campbell-Hausdorff (BCH)/ formula gives
\[
e^{\alpha a^\dagger} e^{\beta a} = e^{-\alpha\beta}e^{\beta a}e^{\alpha a^\dagger} 
\]
We now need to introduce generators with /parameters/ and relations
which can depend on those parameters. This will involve promoting
~gen~ to a type ~Gen~, and ~Braid~ to a parameterized form ~BraidF~:

#+BEGIN_SRC haskell
ladder :: Algebra
ladder = Presentation gen [BraidF φ gen
                         , ParamMonoid f (+) 0
                         , ParamMonoid g (+) 0
                         , StarSwap gen
                         ]
    where gen = [f, g]
           f :: Complex -> Gen
           g :: Complex -> Gen
       φ α β = exp (α * β) 
#+END_SRC

where ~ParamMonoid (+)~ indicates that $f(\alpha) = e^{\alpha a}$ and
$f(\beta) = e^{\beta a^\dagger}$ are "monoids" with respect to
addition, e.g.
\[
f(\alpha + \alpha') = f(\alpha)f(\alpha'),
\]
while ~StarSwap~ indicates that generators are interchanged under the
Hermitian conjugate, e.g.
\[
f(\alpha)^\dagger = (e^{\alpha a})^\dagger =
e^{\overline{\alpha}a^\dagger} = g(\overline{\alpha}).
\]
Although this space is infinite-dimensional, we can still
effectively deal with it using /lazy evaluation/, a strategy we
discuss elsewhere.
** States
In the usual approach, a state $|\psi\rangle$ is a vector on which
operators can act, $|\psi\rangle \mapsto \mathcal{O}|\psi\rangle$. In the
algebraic approach, a state is instead an /expectation/:
\[
\mathcal{O} \mapsto \langle \psi|\mathcal{O}|\psi\rangle := \psi(\mathcal{O}).
\]
Thus, we view $\psi$ as a /linear functional/ (scalar-valued linear
function) rather than a vector.
When $|\psi\rangle$ is an eigenvector of a Hermitian operator $\Lambda$, we have
\[
\Lambda |\psi\rangle = \lambda |\psi\rangle \quad \Longrightarrow
\psi(\mathcal{O}\Lambda) = \lambda\psi(\mathcal{O}) = \psi(\mathcal{O})\psi(\Lambda)
,\]
and similarly
$\psi(\Lambda\mathcal{O})=\psi(\Lambda)\psi(\mathcal{O})$.
This /factorization/ property, along with the value $\lambda$, is a helpful way of
specifying which functional we are talking about.

As a familiar example, we can recast the familiar single-qubit state
$|0\rangle$ as a functional
$\psi_0(\mathcal{O}) = \langle 0|\mathcal{O}|0\rangle$ satisfying
\[
\psi_0(Z \mathcal{O}) = \psi_0(\mathcal{O})\psi_0(Z) = \psi_0(\mathcal{O}
Z), \quad \psi_0(Z) = 1.
\]
In ~Yaw~, this takes the form

#+BEGIN_SRC haskell
state0 :: State pauli
state0 = eigen z (spec z 0)
#+END_SRC

where
- ~State pauli~ is the type of states on the algebra ~pauli~;
- ~eigen z~ identifies this has the factorization property wrt ~z~;
- ~spec z~ lists eigenvalues of ~z~ from largest (at
  $0$) to smallest; thus
- ~spec z 0~ picks out the largest eigenvalue, $\lambda = +1$.

We could define $\psi_1(\mathcal{O}) = \langle 1|A|1\rangle$ analogously, but
it's more revealing to note that
\[
\psi_1(\mathcal{O}) = \langle 1|\mathcal{O}|1\rangle = \langle 0|X \mathcal{O} X|0\rangle = \psi_0(X \mathcal{O} X).
\]
This pattern is common enough to justify two new pieces of notation:
\[
A \triangleright \mathcal{O} = A^\dagger \mathcal{O} A, \quad A
\triangleleft \psi(\mathcal{O}) = \psi(A \triangleright \mathcal{O}) =
\psi(A^\dagger \mathcal{O} A).
\]
We call $\triangleright$ the /operator conjugator/ and $\triangleleft$
the /state conjugator/. These are respectively accomplished by ~<|~ and
~|>~  in ~Yaw~. The argument above shows that $\psi_1 = X
\triangleleft \psi_0$, so in ~Yaw~, using infix notation ~(<|)~ so
conjugation can be prepended as a binary operator:

#+BEGIN_SRC haskell
state1 :: State pauli
state1 = (<|) x state0
#+END_SRC

When states are thought of as functionals, we cannot add them in the usual way. For instance, although adding $|0\rangle$ and $|1\rangle$ results in
\[
\frac{1}{\sqrt{2}}(|0\rangle + |1\rangle) = |+\rangle,
\]
adding the corresponding functionals $\psi_0$ and $\psi_1$ is proportional to the trace (the
maximally mixed state) rather than the pure state $\psi_+$. We have a
totally different thing! To recover the vector addition, we note that $H \triangleleft \psi_0 =\psi_+$, and hence

#+BEGIN_SRC haskell
statePlus :: State pauli
statePlus = (<|) h state0
#+END_SRC

The moral: think like a functional, not like a vector!
A benefit of thinking this way is that /expectation values/
become simple to compute. For instance, the expected value of $Z$
in the $\psi_+$ state is
\[
\psi_+(Z) = \psi_0(HZH) = \psi_0(XH^2) = \psi_0(X) = 0,
\]
using the identities $HZ = XH$, $H^2 = I$ and $\langle 0|X|0\rangle = 0$. Working in the interpreter:

#+BEGIN_SRC elisp
Yaw> statePlus z
0
#+END_SRC

which is evaluated using the same logic internally.

** Tensor products
A state on multiple qubits lives in a /tensor product/ of algebras,
built from tensor products of operators:
\[
\mathcal{A}_\text{Pauli} \otimes \mathcal{A}_\text{Pauli} = \{\mathcal{O}
\otimes \mathcal{O}': \mathcal{O}, \mathcal{O}' \in \mathcal{A}_\text{Pauli}\}.
\]
(There are some technicalities regarding metric completion here that we happily ignore.)
We can add and multiply tensor products. Both operations come into play when we want to use /controlled/ operations. To see how, consider the projectors onto eigenvalues of $Z$:
\[
\Pi^{(Z)}_{b} = \frac{1}{2}\big[I - (-1)^bZ\big], \quad Z = \Pi^{(Z)}_0 - \Pi^{(Z)}_1,
\quad I =\Pi^{(Z)}_0 + \Pi^{(Z)}_1.
\]
These are dual to the eigenfunctionals $\pi_a$ in the sense that $\pi_a(\Pi^{(Z)}_b) = \delta_{ab}$, for binary variables $a, b\in \{0, 1\}$. In ~Yaw~, we define the projectors as follows:

#+BEGIN_SRC haskell
projZ BinDigit :: Pauli
projZ b = (1/2)*(id + (-1)^b z)
#+END_SRC

where ~id~ is the identity and ~BinDigit~ is the type of a binary digit.
A controlled operation like $\text{CNOT}$ applies
$X^a$ when the first state is $\pi_a$, or
\[
\text{CNOT} = \Pi^{(Z)}_0 \otimes I + \Pi^{(Z)}_1 \otimes X = \Pi^{(Z)}_a \otimes X^a,
\]
where we sum over $a = 0, 1$. To implement this, we introduce a tensor product operator ~><~ we use both for individual tensor products and tensor products of types:

#+BEGIN_SRC haskell
cnot :: (><) [pauli, pauli]
cnot = projZ 0 >< id + projZ 1 >< x
#+END_SRC

Similarly, we can define a general controlled operator on ~alg~:

#+BEGIN_SRC haskell
c :: (><) [pauli, alg]
c op = projZ 0 >< id + projZ 1 >< op
#+END_SRC

so ~cnot~ equals ~c x~, as we expect.
* COMMENT html export
#+TITLE:
#+HTML_CONTAINER: div
#+HTML_DOCTYPE: xhtml-strict
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="enhanced_tufte.css">
#+HTML_HEAD: <script type="text/javascript" src="sidebar_darkmode.js"></script>
#+HTML_HEAD: <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
#+HTML_HEAD: <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
#+HTML_LINK_UP:
#+HTML_MATHJAX: 
#+INFOJS_OPT:
#+LATEX_HEADER:
#+OPTIONS: html-postamble:nil toc:nil 
#+HTML_HEAD_EXTRA: <style>pre { padding-top: 25px !important; }</style>
