#+ATTR_HTML: :alt wizard image :align center :width 200px :style display:inline;margin:-20px;
[[https://torsor.io/#community][file:./img/wizard2.png]]

~yaw~ is a domain-specific functional language for programming quantum
computers. This tutorial introduces some basic concepts, assuming
a first course in quantum computing but no further mathematical background.

* Basic concepts
-----
** Algebras
Usually, quantum computing is formulated in terms of states living in
a Hilbert space. In the algebraic approach, we instead use
/observables/ living in an /algebra/. A simple example is the /Pauli
algebra/ $\mathcal{A}_\text{Pauli}$, consisting of all single-qubit
operators. In ~yaw~, we define an object called ~pauli~ and give it
the /type/ of ~Algebra~ as follows:

#+BEGIN_SRC haskell
pauli :: Algebra
#+END_SRC

In general, types are categories of object; by convention, types are
capitalized and objects are not. To actually define
$\mathcal{A}_\text{Pauli}$, we use a /presentation/, consisting of
/generators/ (like ingredients in a recipe) and /relations/ (the
recipe itself). For instance, the Pauli algebra is generated by the
Pauli $X$ and Pauli $Z$, subject to the following relations:
\[
XZ = -ZX, \quad X^\dagger X = X^2 = Z^\dagger Z = Z^2 = I.
\]
Rather than list these individually, we have shorthands which state
that our generators are unitary ($G^\dagger G = I$ for all generators $G$), Hermitian
($G^\dagger = G$ for all $G$) and anticommute ($G'G = -GG'$ for all distinct
generators $G, G'$):

#+BEGIN_SRC haskell
pauli = Presentation gen [Hermitian gen, Unitary gen, AntiComm gen]
    where gen = [x, z]
#+END_SRC

Another way of viewing anticommutation is that $X$ and $Z$ commute up to
a phase $\omega = -1$, often called a /braiding/ relation:
\[
XZ = \omega ZX.
\]
We use ~Braid ω~ to indicate braiding relations. Similarly, instead of
the relation $G^2 = I$ (which results from unitarity) we can introduce
~Pow 2~ to indicate that generators square to the identity. As a
result of this new notation, we can immediately define the algebra of
/qudits/, the $d$-dimensional analogue of qubits:

#+BEGIN_SRC haskell
pauliQudit :: Integer -> Algebra
pauliQudit d = Presentation gen [Hermitian gen, Pow d gen, Braid ω gen]
    where gen = [x, z]
            ω = cis (-2 * pi / d)
#+END_SRC

Note that the type of ~pauliQudit~ is not an algebra, but rather a
/function/ from integers (the dimension) to an algebra (the
generalized Pauli algebra).
We symbolically denote this generalized
algebra $\mathcal{A}_d$, so for instance
$\mathcal{A}_2=\mathcal{A}_\text{Pauli}$.

As a final example, we can encode the commutation relations $[a,
a^\dagger] = I$ for a harmonic oscillator in braiding
form. Applying the /Baker-Campbell-Hausdorff (BCH)/ formula gives
\[
e^{\alpha a^\dagger} e^{\beta a} = e^{-\alpha\beta}e^{\beta a}e^{\alpha a^\dagger} 
\]
We now need to introduce generators with /parameters/ and relations
which can depend on those parameters. This will involve promoting
~gen~ to a type ~Gen~, and ~Braid~ to a parameterized form ~BraidF~:

#+BEGIN_SRC haskell
ladder :: Algebra
ladder = Presentation gen [BraidF φ gen
                           , ParamMonoid f (+) 0
                           , ParamMonoid g (+) 0
                           , StarSwap gen
                          ]
    where gen = [f, g]
           f :: Complex -> Gen
           g :: Complex -> Gen
       φ α β = exp (- α * β) 
#+END_SRC

where ~ParamMonoid (+)~ indicates that $f(\alpha) = e^{\alpha a}$ and
$f(\beta) = e^{\beta a^\dagger}$ are "monoids" with respect to
addition, e.g.
\[
f(\alpha + \alpha') = f(\alpha)f(\alpha'),
\]
while ~StarSwap~ indicates that generators are interchanged under the
Hermitian conjugate, e.g.
\[
f(\alpha)^\dagger = (e^{\alpha a})^\dagger =
e^{\overline{\alpha}a^\dagger} = g(\overline{\alpha}).
\]
Although this space is infinite-dimensional, we can still
effectively deal with it using /lazy evaluation/, a strategy we
discuss elsewhere.
** States
** Channels
* COMMENT html export
#+TITLE:
#+HTML_CONTAINER: div
#+HTML_DOCTYPE: xhtml-strict
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="enhanced_tufte.css">
#+HTML_HEAD: <script type="text/javascript" src="sidebar_darkmode.js"></script>
#+HTML_HEAD: <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
#+HTML_HEAD: <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
#+HTML_LINK_UP:
#+HTML_MATHJAX: 
#+INFOJS_OPT:
#+LATEX_HEADER:
#+OPTIONS: html-postamble:nil toc:nil 
#+HTML_HEAD_EXTRA: <style>pre { padding-top: 25px !important; }</style>
